# Linear Algebra in Numpy

In [9]:
import numpy as np
np.random.seed(0)

In [23]:
a = np.random.normal(0, 1, size = 3)
print(a.shape)

(3,)


In [24]:
# perform a dot product
a@a

2.71483840254408

In [25]:
# perform a dot product
b = a@a.T
b

2.71483840254408

In [26]:
# perform a column vector times a row vector
c = a.T@a
c

2.71483840254408

In [27]:
print(a)
# element wise multiplication (Hadamard Product)
print(np.multiply(a,a))

[0.14404357 1.45427351 0.76103773]
[0.02074855 2.11491143 0.57917842]


In [29]:
np.multiply(a.T, a)

array([0.02074855, 2.11491143, 0.57917842])

In [39]:
# Compute outer product (i.e., a.T @ a)
d = np.outer(a, a)
print(d)
print(d.shape)

[[0.02074855 0.20947875 0.10962259]
 [0.20947875 2.11491143 1.106757  ]
 [0.10962259 1.106757   0.57917842]]
(3, 3)


In [40]:
d*d

array([[4.30502343e-04, 4.38813464e-02, 1.20171126e-02],
       [4.38813464e-02, 4.47285037e+00, 1.22491106e+00],
       [1.20171126e-02, 1.22491106e+00, 3.35447641e-01]])

In [41]:
np.outer(d, d).shape

(9, 9)